version: '3'
services:
  postgres:
    image: postgres:14
    restart: always
    container_name: banco-produtos
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=produtos-apirest
    ports:
      - '5415:5432'
    volumes:
      - ./docker/volume-postgres:/var/lib/postgres